// Long Chau Care — Data Constants

const I = "/assets/icons";
const M = "/assets/mascots_nobg";

export const ICONS = {
  // Nav
  nav_home: `${I}/nav_home.webp`,
  nav_family: `${I}/nav_family.webp`,
  nav_calendar: `${I}/nav_calendar.webp`,
  nav_careplan: `${I}/nav_careplan.webp`,
  nav_profile: `${I}/nav_profile.webp`,

  // Plants
  plant_ginger: `${I}/plant_ginger.webp`,
  plant_turmeric: `${I}/plant_turmeric.webp`,
  plant_lemongrass: `${I}/plant_lemongrass.webp`,
  plant_pennywort: `${I}/plant_pennywort.webp`,
  plant_lotus: `${I}/plant_lotus.webp`,
  plant_perilla: `${I}/plant_perilla.webp`,
  plant_tea: `${I}/plant_tea.webp`,
  plant_mint: `${I}/plant_mint.webp`,
  plant_basil: `${I}/plant_basil.webp`,
  plant_aloe: `${I}/plant_aloe.webp`,
  plant_licorice: `${I}/plant_licorice.webp`,
  plant_bittermelon: `${I}/plant_bittermelon.webp`,
  plant_lavender: `${I}/plant_lavender.webp`,
  plant_ginseng: `${I}/plant_ginseng.webp`,
  plant_eucommia: `${I}/plant_eucommia.webp`,
  plant_phyllanthus: `${I}/plant_phyllanthus.webp`,

  // Avatars
  avatar_mom: `${I}/avatar_mom.webp`,
  avatar_dad: `${I}/avatar_dad.webp`,
  avatar_grandma: `${I}/avatar_grandma.webp`,
  avatar_child: `${I}/avatar_child.webp`,

  // Badges
  badge_sprout: `${I}/badge_sprout.webp`,
  badge_tree: `${I}/badge_tree.webp`,
  badge_garden: `${I}/badge_garden.webp`,
  badge_family: `${I}/badge_family.webp`,

  // Vouchers
  voucher_lab: `${I}/voucher_lab.webp`,
  voucher_vaccine: `${I}/voucher_vaccine.webp`,
  voucher_supplement: `${I}/voucher_supplement.webp`,

  // UI System
  ui_check_circle: `${I}/ui_check_circle.webp`,
  ui_pending_clock: `${I}/ui_pending_clock.webp`,
  ui_error_cross: `${I}/ui_error_cross.webp`,
  ui_warning_triangle: `${I}/ui_warning_triangle.webp`,
  ui_lock_closed: `${I}/ui_lock_closed.webp`,
  ui_back_arrow: `${I}/ui_back_arrow.webp`,
  ui_expand_down: `${I}/ui_expand_down.webp`,
  ui_collapse_up: `${I}/ui_collapse_up.webp`,
  ui_delete_trash: `${I}/ui_delete_trash.webp`,
  ui_share_forward: `${I}/ui_share_forward.webp`,
  ui_water_drop: `${I}/ui_water_drop.webp`,
  ui_fire_streak: `${I}/ui_fire_streak.webp`,
  ui_pill_medicine: `${I}/ui_pill_medicine.webp`,
  ui_heart_health: `${I}/ui_heart_health.webp`,
  ui_calendar_date: `${I}/ui_calendar_date.webp`,
  ui_lightbulb_insight: `${I}/ui_lightbulb_insight.webp`,
  ui_document_clipboard: `${I}/ui_document_clipboard.webp`,
  ui_chart_bar: `${I}/ui_chart_bar.webp`,
  ui_trend_up: `${I}/ui_trend_up.webp`,
  ui_bell_notification: `${I}/ui_bell_notification.webp`,
  ui_gift_box: `${I}/ui_gift_box.webp`,
  ui_trophy_cup: `${I}/ui_trophy_cup.webp`,
  ui_graduate_cap: `${I}/ui_graduate_cap.webp`,
  ui_party_celebrate: `${I}/ui_party_celebrate.webp`,
  ui_medal_badge: `${I}/ui_medal_badge.webp`,
  ui_pharmacist: `${I}/ui_pharmacist.webp`,
  ui_store_pharmacy: `${I}/ui_store_pharmacy.webp`,
  ui_note_pencil: `${I}/ui_note_pencil.webp`,
  ui_points_grain: `${I}/ui_points_grain.webp`,

  // Mascots
  mascot: `${M}/mascot_avatar.webp`,
  mascot_avatar: `${M}/mascot_avatar.webp`,
  mascot_loading: `${M}/mascot_loading.webp`,
  mascot_insight: `${M}/mascot_insight.webp`,
  mascot_approval: `${M}/mascot_approval.webp`,
  mascot_welcome: `${M}/mascot_welcome.webp`,
  mascot_pharmacist: `${M}/mascot_pharmacist_partner.webp`,
  mascot_family: `${M}/mascot_family.webp`,
  mascot_expressions: `${M}/mascot_expressions.webp`,
  mascot_ui_kit: `${M}/mascot_ui_kit.webp`,
  mascot_watering: `${M}/mascot_watering.webp`,

  // Logo
  app_logo: `${I}/app_logo.webp`,
};

export const PLANTS_DATA = {
  ginger: {
    id: "ginger",
    name: "Cây Gừng",
    emoji: "🫚",
    icon: ICONS.plant_ginger,
    journeyCode: "health_care",
    journeyLabel: "Chăm sóc sức khỏe",
    story: "Vị ấm, giải cảm, đồng hành sáng tối",
    whyThisPlant: "Gừng giúp lưu thông máu, ổn định huyết áp — phù hợp với hành trình chăm sóc tim mạch mỗi ngày",
    color: "#00923F",
    colorPale: "#E8F5EE",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: "DS Nguyễn Thị Lan",
    plantStatus: "growing",
  },
  turmeric: {
    id: "turmeric",
    name: "Cây Nghệ",
    emoji: "🟡",
    icon: ICONS.plant_turmeric,
    journeyCode: "monitoring",
    journeyLabel: "Theo dõi chỉ số",
    story: "Chống viêm, kiên trì hồi phục",
    whyThisPlant: "Nghệ tượng trưng cho sự kiên nhẫn — theo dõi chỉ số đều đặn để thấy kết quả rõ rệt theo thời gian",
    color: "#D97706",
    colorPale: "#FEF3C7",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "lab_with_doctor",
    conditionVerifiedBy: null,
    plantStatus: "pending",
  },
  lemongrass: {
    id: "lemongrass",
    name: "Cây Sả",
    emoji: "🌿",
    icon: ICONS.plant_lemongrass,
    journeyCode: "prevention",
    journeyLabel: "Phòng ngừa",
    story: "Thanh lọc, thải độc, vận động cùng cây",
    whyThisPlant: "Sả thanh lọc cơ thể tự nhiên — đồng hành cùng bạn xây dựng thói quen vận động và phòng ngừa bệnh",
    color: "#4A8A40",
    colorPale: "#E4F2DC",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "self_report",
    conditionVerifiedBy: null,
    plantStatus: "growing",
  },
  pennywort: {
    id: "pennywort",
    name: "Cây Rau Má",
    emoji: "🌾",
    icon: ICONS.plant_pennywort,
    journeyCode: "screening",
    journeyLabel: "Khám định kỳ",
    story: "Mát gan, đều đặn chăm sóc",
    whyThisPlant: "Rau Má nhắc nhở sự đều đặn — giống như khám định kỳ, chăm sóc một chút mỗi ngày tạo nên sức khỏe lâu dài",
    color: "#0284C7",
    colorPale: "#F0F9FF",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "citizen_station",
    conditionVerifiedBy: null,
    plantStatus: "pending",
  },
  lotus: {
    id: "lotus",
    name: "Cây Hoa Sen",
    emoji: "🪷",
    icon: ICONS.plant_lotus,
    journeyCode: "maternity",
    journeyLabel: "Thai sản",
    story: "Vươn lên từ bùn, nở hoa kiêu hãnh",
    whyThisPlant: "Hoa Sen tượng trưng cho sự sinh sôi và kiên cường — đồng hành cùng mẹ bầu trong hành trình thai kỳ an toàn",
    color: "#DB2777",
    colorPale: "#FCE7F3",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: "DS Trần Thị Hoa",
    plantStatus: "growing",
  },
  perilla: {
    id: "perilla",
    name: "Cây Tía Tô",
    emoji: "🍃",
    icon: ICONS.plant_perilla,
    journeyCode: "pediatric",
    journeyLabel: "Nhi khoa",
    story: "Lá lành chữa lành, bảo vệ mầm non",
    whyThisPlant: "Tía Tô là bài thuốc dân gian quen thuộc cho trẻ nhỏ — nhắc nhở bạn bảo vệ sức khỏe của bé mỗi ngày",
    color: "#C4607A",
    colorPale: "#FDEEF4",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "self_report",
    conditionVerifiedBy: null,
    plantStatus: "pending",
  },
  tea: {
    id: "tea",
    name: "Cây Lá Trà",
    emoji: "🍵",
    icon: ICONS.plant_tea,
    journeyCode: "long_term_adherence",
    journeyLabel: "Tuân thủ dài hạn",
    story: "Chậm rãi, kiên định, nuôi dưỡng",
    whyThisPlant: "Trà cần thời gian ủ để ngon — giống như uống thuốc đều đặn, kiên trì mỗi ngày mới thấy hiệu quả",
    color: "#3B82F6",
    colorPale: "#EFF6FF",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: "DS Lê Văn Minh",
    plantStatus: "growing",
  },
  mint: {
    id: "mint",
    name: "Cây Bạc Hà",
    emoji: "🌿",
    icon: ICONS.plant_mint,
    journeyCode: "g1",
    journeyLabel: "Sức khỏe nền tảng",
    story: "Thơm mát, tỉnh táo mỗi ngày",
    whyThisPlant: "Bạc Hà mang năng lượng tươi mới — phù hợp để xây dựng nền tảng sức khỏe cơ bản hàng ngày",
    color: "#10B981",
    colorPale: "#D1FAE5",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "self_report",
    conditionVerifiedBy: null,
    plantStatus: "growing",
  },
  basil: {
    id: "basil",
    name: "Cây Húng Quế",
    emoji: "🌿",
    icon: ICONS.plant_basil,
    journeyCode: "g5",
    journeyLabel: "Dinh dưỡng",
    story: "Tăng cường đề kháng, sinh lực",
    whyThisPlant: "Húng Quế giàu dưỡng chất — nhắc bạn bổ sung dinh dưỡng đầy đủ để cơ thể luôn khỏe mạnh",
    color: "#F59E0B",
    colorPale: "#FEF3C7",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "self_report",
    conditionVerifiedBy: null,
    plantStatus: "growing",
  },
  aloe: {
    id: "aloe",
    name: "Cây Lô Hội",
    emoji: "🪴",
    icon: ICONS.plant_aloe,
    journeyCode: "g6",
    journeyLabel: "Da liễu, Dị ứng",
    story: "Dịu mát, chữa lành",
    whyThisPlant: "Lô Hội nổi tiếng làm dịu và phục hồi da — đồng hành cùng bạn chăm sóc và bảo vệ làn da mỗi ngày",
    color: "#059669",
    colorPale: "#D1FAE5",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "self_report",
    conditionVerifiedBy: null,
    plantStatus: "growing",
  },
  licorice: {
    id: "licorice",
    name: "Cây Cam Thảo",
    emoji: "🌿",
    icon: ICONS.plant_licorice,
    journeyCode: "g11",
    journeyLabel: "Điều trị đa khoa",
    story: "Điều hòa, ngọt ngào vững chắc",
    whyThisPlant: "Cam Thảo điều hòa nhiều cơ quan — phù hợp khi bạn cần chăm sóc sức khỏe toàn diện trên nhiều mặt",
    color: "#B45309",
    colorPale: "#FEF3C7",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: "DS Nguyễn Thị Lan",
    plantStatus: "growing",
  },
  bittermelon: {
    id: "bittermelon",
    name: "Cây Khổ Qua",
    emoji: "🥒",
    icon: ICONS.plant_bittermelon,
    journeyCode: "g3",
    journeyLabel: "Chuyển hóa",
    story: "Đắng trước ngọt sau, cân bằng cuộc sống",
    whyThisPlant: "Khổ Qua hỗ trợ cân bằng chuyển hóa — nhắc bạn kiên trì với thói quen lành mạnh để thấy kết quả ngọt ngào",
    color: "#65A30D",
    colorPale: "#ECFCCB",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: "DS Nguyễn Thị Lan",
    plantStatus: "growing",
  },
  lavender: {
    id: "lavender",
    name: "Cây Oải Hương",
    emoji: "🪻",
    icon: ICONS.plant_lavender,
    journeyCode: "g8",
    journeyLabel: "Thần kinh",
    story: "Hương thơm thư giãn, giấc ngủ sâu",
    whyThisPlant: "Oải Hương giúp an thần tự nhiên — đồng hành cùng bạn giảm stress và cải thiện giấc ngủ mỗi tối",
    color: "#7C3AED",
    colorPale: "#EDE9FE",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "self_report",
    conditionVerifiedBy: null,
    plantStatus: "growing",
  },
  ginseng: {
    id: "ginseng",
    name: "Cây Nhân Sâm",
    emoji: "🥔",
    icon: ICONS.plant_ginseng,
    journeyCode: "g9",
    journeyLabel: "Phục hồi",
    story: "Tinh hoa đất trời, trường thọ an khang",
    whyThisPlant: "Nhân Sâm bổ khí, phục hồi sức lực — phù hợp khi bạn đang hồi phục sức khỏe sau giai đoạn khó khăn",
    color: "#9CA3AF",
    colorPale: "#F3F4F6",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: "DS Nguyễn Thị Lan",
    plantStatus: "growing",
  },
  eucommia: {
    id: "eucommia",
    name: "Cây Đỗ Trọng",
    emoji: "🌳",
    icon: ICONS.plant_eucommia,
    journeyCode: "bone_joint",
    journeyLabel: "Xương khớp",
    story: "Vững vàng như cây cổ thụ, xương chắc khỏe mỗi ngày",
    whyThisPlant: "Đỗ Trọng bổ xương cốt, chắc gân cơ — nhắc bạn vận động và chăm sóc xương khớp đều đặn",
    color: "#8B5CF6",
    colorPale: "#EDE9FE",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: null,
    plantStatus: "pending",
  },
  phyllanthus: {
    id: "phyllanthus",
    name: "Cây Diệp Hạ Châu",
    emoji: "🌿",
    icon: ICONS.plant_phyllanthus,
    journeyCode: "digestive",
    journeyLabel: "Tiêu hóa / Gan",
    story: "Mát gan, thanh nhiệt, nhẹ nhàng thải độc",
    whyThisPlant: "Diệp Hạ Châu mát gan, thanh nhiệt tự nhiên — đồng hành cùng bạn bảo vệ hệ tiêu hóa và chức năng gan",
    color: "#059669",
    colorPale: "#D1FAE5",
    stageNames: ["Chờ duyệt", "Mầm non", "Cây non", "Trưởng thành", "Đang nụ", "Nở hoa"],
    conditionSource: "doctor_prescription",
    conditionVerifiedBy: null,
    plantStatus: "pending",
  },
};

export const BADGES = [
  { emoji: "🌱", icon: ICONS.badge_sprout, name: "Mầm Xanh", desc: "7 ngày streak", days: 7 },
  { emoji: "🌿", icon: ICONS.badge_tree, name: "Cây Lớn", desc: "14 ngày streak", days: 14 },
  { emoji: "🌳", icon: ICONS.badge_garden, name: "Vườn Xanh", desc: "30 ngày streak", days: 30 },
  { emoji: "👨‍👩‍👧", icon: ICONS.badge_family, name: "Gia đình khỏe", desc: "Cả nhà streak > 7", days: 7 },
];

export const VOUCHERS = [
  { id: "lab", icon: "🧪", iconImg: ICONS.voucher_lab, type: "Long Châu Lab", desc: "Xét nghiệm HbA1c + Lipid máu miễn phí", cost: 500, value: "Miễn phí" },
  { id: "vacc", icon: "💉", iconImg: ICONS.voucher_vaccine, type: "Tiêm chủng", desc: "Giảm 50.000đ gói cúm + phế cầu", cost: 500, value: "-50k" },
  { id: "supp", icon: "🐟", iconImg: ICONS.voucher_supplement, type: "TPCN", desc: "Giảm 30.000đ Omega-3 Fish Oil", cost: 300, value: "-30k" },
];

export const CONDITION_SOURCE_TYPES = {
  doctor_prescription: "Đơn thuốc bác sĩ",
  lab_with_doctor: "Xét nghiệm có bác sĩ chỉ định",
  vneid: "VNeID (liên thông Bộ Y tế)",
  self_report: "Khách hàng tự khai",
  citizen_station: "Trạm y tế phường",
};

/** Guardrail #3: Cây KHÔNG BAO GIỜ chết — không có 'dead' */
export const PLANT_STATUS = {
  pending: "Chờ duyệt",
  growing: "Đang lớn",
  paused: "Tạm dừng",
  graduated: "Tốt nghiệp",
};
